### ISSUE TITLE
Circle code shape can not be recognized

### ISSUE THREAD

**Issue by jaracle** [alexzhirkevich/custom-qr-generator#11]
Change codeShape property from default to QrShape.circle(), will cause qr code can not be recognized.

**Comment by alexzhirkevich** [comment]
Try decrease logo size and set `errorCorrectionLevel` to High

**Comment by alexzhirkevich** [comment]
From 1.5.51 error correction level of vector codes is set to `Auto` by default and works better with custom code shapes.
