### ISSUE TITLE
Use custom logo from gallery

### ISSUE THREAD

**Issue by neelniloy** [alexzhirkevich/custom-qr-generator#12]
is there any way to use URI or Bitmap for the logo image?

**Comment by alexzhirkevich** [comment]
You can use `BitmapDrawable` and create custom `DrawableSource`:

```kotlin
val bitmapDrawableSource = DrawableSource { BitmapDrawable(yourBitmap) }
```

If URI is from android file system, you can use `DrawableSource.File`

**Comment by neelniloy** [comment]
Thanks. Issue Solved
