### ISSUE TITLE
Central symmetry of shapes

### ISSUE THREAD

**Issue by alexzhirkevich** [alexzhirkevich/custom-qr-generator#13]
How to customise eyes like this, i tried and able to customise with same shape but all the sides are same! how to differentiate left top,  right top and left bottom eye side? 
![unitag_qrcode_standard](https://user-images.githubusercontent.com/4948894/210740615-389e71e3-9184-4902-a406-dd5365255a9f.png)

_Originally posted by @hardikbhalodi in https://github.com/alexzhirkevich/custom-qr-generator/issues/8#issuecomment-1371942600_

**Comment by alexzhirkevich** [comment]
# For vector codes only

From 1.5.5 central symmetry is enabled by default and can be changed with 

```kotlin
val options = createVectorOptions {
    shapes(centralSymmetry = enabled){
        /// .....
    }
}
```

Or in builder :

```kotlin
val shapes = QrVectorShapes(
    centralSymmetry = enabled,
    frame = ...,
    ball = ...
)
```

**Comment by hardikbhalodi** [comment]
Thanks, i will check it out

**Comment by alexzhirkevich** [comment]
> ```
>     How to customise eyes like this, i tried and able to customise with same shape but all the sides are same! how to differentiate left top,  right top and left bottom eye side? 
> ```
> 
> 
>      
>   
> 
> ![unitag_qrcode_standard](https://user-images.githubusercontent.com/4948894/210740615-389e71e3-9184-4902-a406-dd5365255a9f.png)
> 
> 
> _Originally posted by @hardikbhalodi in [#8 (comment)](https://github.com/alexzhirkevich/custom-qr-generator/issues/8#issuecomment-1371942600)_

Shape like this now can be created using `bottomRight = false` property in `QrVectorFrameShape.RoundCorners` and `QrVectorBallShape.RoundCorners` constructors
