### ISSUE TITLE
When QR code has more than 800 characters and adding a logo, it taking 4 to 5 seconds to apply

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#15]

**Comment by hardikbhalodi** [comment]
When QR code has more than 800 characters and adding a logo it taking time and sometime hang the app

**Comment by alexzhirkevich** [comment]
Avoid using `QrVectorLogoPadding.Accutate` with large QR codes. Use `QrVectorLogoPadding.Natural` padding or don't use logo padding at all if it possible.

**Comment by hardikbhalodi** [comment]
Okay thanks, will try that thanks.
