### ISSUE TITLE
in v1.5.6 SweepGradient(Array) can not pass the value from java code because of generic array type in kotlin.

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#16]
in 1.5.5 it was SweepGradient(List<Pair<Float, Int>>))  ==> java list is working

in 1.5.6 it is SweepGradient(Array<Pair<Float, Int>>)) ==> here is generic array so can not convert from java to kotlin

**Comment by alexzhirkevich** [comment]
It will be list again in next releases
