### ISSUE TITLE
live app example 

### ISSUE THREAD

**Issue by ThorstenWirth** [alexzhirkevich/custom-qr-generator#18]
In the app please add to the e-mail subject and text-body.

**Comment by alexzhirkevich** [comment]
Hi @ThorstenWirth, i'll probably add this later.

You can just type this in email field: `someone@example.com?cc=someone_else@example.com&subject=This%20is%20the%20subject&body=This%20is%20the%20body` to add copy, subject and body

**Comment by alexzhirkevich** [comment]
Added in 1.0.1
