### ISSUE TITLE
4th ball visibility

### ISSUE THREAD

**Issue by Aijaz-Ali-Shah** [alexzhirkevich/custom-qr-generator#19]
How to visible 4th ball like other three balls
e.g: color, design etc

**Comment by alexzhirkevich** [comment]
It is not available at the moment, but it is quite interesting enhancement . I'll probably add such ability in a future version

**Comment by alexzhirkevich** [comment]
Added in 1.5.8

```kotlin
val options = createQrVectorOptions {
    fourthEyeEnabled = true
}
```

Or

```kotlin
val options = QrVectorOptions.Builder()
    .setFourthEyeEnabled(true)
    .build()
```

**Comment by hardikbhalodi** [comment]
@alexzhirkevich seems 1.5.8 repository not working.

**Comment by alexzhirkevich** [comment]
> @alexzhirkevich seems 1.5.8 repository not working, could not fetch the latest changes.

fixed

**Comment by Aijaz-Ali-Shah** [comment]
Awesome, appreciate your quick response, although I did not upgrade your library right now because it's given me  conflict with my Kotlin version,
"Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0."
 and if I updated Kotlin version then I must be needed to  update hilt version too, so currently I did not have such time to check impact above changes but defiantly I will be try in  future.

**Comment by alexzhirkevich** [comment]
@Aijaz-Ali-Shah Check out new version `1.6.0`. It was build with previous Kotlin version. 1.5.8 was bad overall...
