### ISSUE TITLE
Logo from url 

### ISSUE THREAD

**Issue by lJanusl** [alexzhirkevich/custom-qr-generator#20]
Can you add the option to load a logo from the url and not just from resources? please

Thank you for your work, is very nice this library.

**Comment by alexzhirkevich** [comment]
You can load logo drawable by yourself, for example using `Glide` and create custom `DrawableSource`. Is it public interface.

But don't load logo inside `DrawableSource.get` method.
 It is `suspend` now, but is runs blocking in `QrCodeDrawable` and it will not more be suspend in next version

**Comment by lJanusl** [comment]
thanks a lot!
