### ISSUE TITLE
Version 1.5.8 setFourthEyeEnabled() method ambiguous call in Java 

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#21]
![Screenshot_2023-03-10_15-32-32](https://user-images.githubusercontent.com/4948894/224287792-f687aaf7-fd27-4646-aebf-b6dcdd8df9d4.png)

**Comment by alexzhirkevich** [comment]
Fixed. When you guys stop using java for android development ...

**Comment by alexzhirkevich** [comment]
If you want to implement version from commit, you can always get it [here](https://jitpack.io/#alexzhirkevich/custom-qr-generator) in `commits` section
