### ISSUE TITLE
Need option for Padding/Margin for QrVectorBackground Image

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#25]
Right now lib has feature **options.setPadding()** which apply only to the QrCodeDrawable but when set background image it apply to whole area. Can we have that feature so we can give desire padding/margin to the background image too?

**Comment by alexzhirkevich** [comment]
<table>
<tr>
<td>
<img width="300" alt="image" src="https://user-images.githubusercontent.com/63979218/229036781-41a2ddea-cfc2-4101-a614-3a0a033c80cf.png">
</td>
<td>

```kotlin
createQrVectorOptions {    
    background {
        drawable = ContextCompat.getDrawable(
             this@MainActivity, R.drawable.frame
        )
    }
}
```

</td>
</tr>
<tr>
<td>
<img width="300" alt="image" src="https://user-images.githubusercontent.com/63979218/229037493-cdf18d21-2d7b-4794-8e15-376c9047191f.png">
</td>
<td>

```kotlin
createQrVectorOptions {    
    background {
        drawable = InsetDrawable(
            ContextCompat.getDrawable(
                this@MainActivity, R.drawable.frame)!!, 
            .1f
        )
    }
}
```

</td>
</table>

**Comment by hardikbhalodi** [comment]
![Screenshot_20230403_184625](https://user-images.githubusercontent.com/4948894/229521126-9422dbcd-780d-42cd-a084-b4caa913d7f8.png)
![Screenshot_20230403_184532](https://user-images.githubusercontent.com/4948894/229521139-9ba055db-658d-4e3a-a5e3-2fa4e25d8170.png)

**Comment by hardikbhalodi** [comment]
![Screenshot_20230403_184532](https://user-images.githubusercontent.com/4948894/229521835-f10a335b-c338-42db-83c6-4c693227d783.png)
![Screenshot_20230403_184625](https://user-images.githubusercontent.com/4948894/229521851-7e403c83-84c7-4565-9efa-b129bac92222.png)

**Comment by alexzhirkevich** [comment]
Why don't you just set code padding to 0 and add padding to the ImageView

**Comment by hardikbhalodi** [comment]
I could add padding to the ImageView but it will apply to the view only and
later when creating a drawable the padding will not be there in the
drawable itself.
Thanks for your reply and suggestions. I will check it out.
