### ISSUE TITLE
Logo seems not cropped properly 

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#26]
**Describe the bug**
When set logo with Accurate or Natural padding (0.25) and its not cropping correctly and outline visible, also same issue for all shape circle or round rectangle etc.  i tired with JPG and PNG logo, issue faced for both.

**Versions**
Library : '1.6.1'
Android: 13 
![Screenshot_20230419_113628](https://user-images.githubusercontent.com/4948894/232982917-7d8d0211-a493-4890-9e95-bff1848e760c.png)
![Screenshot_20230419_113643](https://user-images.githubusercontent.com/4948894/232982928-c180400a-0d74-4a5f-acc7-56ea33b635ab.png)

![Screenshot_20230419_113721](https://user-images.githubusercontent.com/4948894/232982954-21e51b82-edcc-4864-925c-32fb8f2cc3b1.png)
![Screenshot_20230419_113704](https://user-images.githubusercontent.com/4948894/232982960-fcaef7b0-1e53-4fc8-a423-6113f56dde32.png)

**Comment by alexzhirkevich** [comment]
Try `8b2a97c5e6` snapshot

**Comment by alexzhirkevich** [comment]
Try 8b2a97c5e6 snapshot

**Comment by hardikbhalodi** [comment]
Seem its fixed in 8b2a97c5e6 but when it is drawable its look strange check the images but after generate bitmap all good

![Screenshot_20230419_135925](https://user-images.githubusercontent.com/4948894/233017093-7829a831-0be3-42bd-b17b-88fa6fc244e8.png)

![Screenshot_20230419_135539](https://user-images.githubusercontent.com/4948894/233017099-12e43c0e-2a47-4647-8cc9-d3395d8baa99.png)

**Comment by alexzhirkevich** [comment]
Only after `8b2a97c5e6` or it was before too?

**Comment by hardikbhalodi** [comment]
Before too!

**Comment by hardikbhalodi** [comment]
This  happening when i am setting logo from phone gallery and convert selected Bitmap to Drawable using below code

Drawable d = new BitmapDrawable(getResources(), bitmap); <=== issue when using this


But i change to this code and all good now.

Drawable d = RoundedBitmapDrawableFactory.create(context.getResources(), 
                bitmap);   < ===  This code fixed the drawable issue.
