### ISSUE TITLE
Long time Generation

### ISSUE THREAD

**Issue by zokirjonkodirov** [alexzhirkevich/custom-qr-generator#3]
Taking too much time to generate Bitmap. On average devices with 1024 size takes about 8 - 10 seconds. How can we reduce generation time?

**Comment by Zokirjon-Ashiraliyev** [comment]
I'm getting this error too

**Comment by alexzhirkevich** [comment]
> Taking too much time to generate Bitmap. On average devices with 1024 size takes about 8 - 10 seconds. How can we reduce generation time?

Upgraded performance up to 40% in 1.2.4. (time reduced from 2500ms to 1500ms on Snapdragon 730 with logo and background image, 1024 size). Tested on Mi-9T, pretty average 2019 device. Can you please specify your device?

Also you can test your app in release build (if you didn't already done it). It reduces generation time by ~15%.

If you generate code only to preview, you can create options with the size of your ImageView. Most of smartphones width is <= 1080p and tablets width is <= 1600p. So i think your ImageView size is smaller than 1024p and 1024p code size is redundant.

**Comment by zokirjonkodirov** [comment]
Size - 1024 
Redmi Note 9 Pro - 2800 ms
Redmi 5 - 30 000 ms
Samsung A10 - 8000ms
Samsung A40 - 1500ms

Size - 512
Redmi Note 9 Pro - 1000 ms
Redmi 5 - 15 000 ms
Samsung A10 - 4000ms

I'll try with release build and share results again.

**Comment by alexzhirkevich** [comment]
> Size - 1024 Redmi Note 9 Pro - 2800 ms Redmi 5 - 30 000 ms Samsung A10 - 8000ms Samsung A40 - 1500ms
> 
> Size - 512 Redmi Note 9 Pro - 1000 ms Redmi 5 - 15 000 ms Samsung A10 - 4000ms
> 
> I'll try with release build and share results again.

Have you tried version 1.2.4? Released it after your issue

**Comment by alexzhirkevich** [comment]
Added multi-thread support. Try it, but read README first.

**Comment by alexzhirkevich** [comment]
Completely fixed in 1.2.5

**Comment by alexzhirkevich** [comment]
Completely fixed in 1.2.5
