### ISSUE TITLE
com.google.zxing.WriterException

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#32]
**Describe the bug**
Caused by com.google.zxing.WriterException:
  at com.google.zxing.qrcode.encoder.Encoder.chooseVersion (Encoder.java:313)
  at com.google.zxing.qrcode.encoder.Encoder.recommendVersion (Encoder.java:213)
  at com.google.zxing.qrcode.encoder.Encoder.encode (Encoder.java:147)
  at com.github.alexzhirkevich.customqrgenerator.vector.QrCodeDrawableImpl.<init> (QrCodeDrawable.kt:44)
  at com.github.alexzhirkevich.customqrgenerator.vector.QrCodeDrawableKt.QrCodeDrawable (QrCodeDrawable.kt:29)

**Versions**
Library : '1.6.2'
Android: '12'

**Comment by alexzhirkevich** [comment]
Probably content is too big. Need a code snippet to reproduce

**Comment by hardikbhalodi** [comment]
When data is big can you  throw that exception so we can display message or do something when exception occurred . Right now app is crashing when data is too big.
```
QrCodeDrawableImpl(
    data: QrData,
    private val options: QrVectorOptions,
    charset: Charset?=null
) : Drawable() {

    private var anchorCenters: List<Pair<Int, Int>>

    private val initialMatrix: QrCodeMatrix

    private val shapeIncrease : Int

    init {
           val code = Encoder.encode(                **<=== if you can throw writer exception or catch it if possible.**
            data.encode(),
            with(options.errorCorrectionLevel) {
                if (this == QrErrorCorrectionLevel.Auto)
                    fit(options.logo, options.codeShape).lvl
                else lvl
            },
            charset?.let {
                mapOf(EncodeHintType.CHARACTER_SET to it)
            })
```

**Comment by hardikbhalodi** [comment]
Yeah but its unchecked so writing try catch with WriterException gives error any way i will do with base exception class thanks for your time.
