### ISSUE TITLE
Add QrVectorPixelShape.Square(size) shape modifier

### ISSUE THREAD

**Issue by michaelWuensch** [alexzhirkevich/custom-qr-generator#34]
**Is your feature request related to a problem? Please describe.**
It seems to be more complicated to create a QR Code with square pixel shapes than it should be.

**Describe the solution you'd like**
There should be a built in QrVectorPixelShape.Square(size) shape modifier

**Describe alternatives you've considered**
Using QrVectorPixelShape.RoundCorners(0f) is different, as the shape cannot be scaled

**Comment by alexzhirkevich** [comment]
Will be added in #35 as `QrVectorPixelShape.Rect(size)`

**Comment by michaelWuensch** [comment]
Awesome, thanks!

**Comment by alexzhirkevich** [comment]
Available in `2.0.0-alpha01`
