### ISSUE TITLE
How to use your library draw QR codes with 3 vertices and circles? Looking forward to your reply

### ISSUE THREAD

**Issue by will12190** [alexzhirkevich/custom-qr-generator#36]
![image](https://github.com/alexzhirkevich/custom-qr-generator/assets/48728107/200e137d-b829-4980-ab8b-406d27b4029a)

Similar to this

**Comment by alexzhirkevich** [comment]
```kotlin
val options = createQrVectorOptions {

    colors {
        dark = QrVectorColor.Solid(0XFF06084D.toColor())
    }

    shapes {
        frame = QrVectorFrameShape.Circle(1f)
        ball = QrVectorBallShape.Circle(1f)
        darkPixel = QrVectorPixelShape.Circle(.85f)
    }
}
```

**Comment by will12190** [comment]
Thank you very much for your reply. I have tested it and it's okay. Thank you, God

**Comment by will12190** [comment]
Hello, could you please ask me again? Today, I suddenly realized that your production has 4 circles. Can you set it to 3 circles?
![telegram-cloud-photo-size-5-6140911546985987114-y](https://github.com/alexzhirkevich/custom-qr-generator/assets/48728107/293af1e1-0fb7-4c1a-b1fd-c6dc9a52bffc)

**Comment by alexzhirkevich** [comment]
> ```kotlin
> val options = createQrVectorOptions {
> 
>     colors {
>         dark = QrVectorColor.Solid(0XFF06084D.toColor())
>     }
> 
>     shapes {
>         frame = QrVectorFrameShape.Circle(1f)
>         ball = QrVectorBallShape.Circle(1f)
>         darkPixel = QrVectorPixelShape.Circle(.85f)
>     }
> }
> ```

The sample mentioned above produces QR code with 3 eyes as a default behavior.

 To enabled 4rd eye you need to set `fourthEyeEnabled = true`. So if you want to disable it you have to remove this line or set this flag to `false`.

**Comment by will12190** [comment]
Thank you for your reply. After testing, it's ready. Thank you again, your friend. Welcome to China to play
