### ISSUE TITLE
Expose reserved areas

### ISSUE THREAD

**Issue by michaelWuensch** [alexzhirkevich/custom-qr-generator#38]
**Is your feature request related to a problem? Please describe.**
I created a QR code design which features randomly selected pixel highlights in my apps accent color.
![Screenshot_20230709_124750_BitBanana Debug~2](https://github.com/alexzhirkevich/custom-qr-generator/assets/15313630/0f38596b-ef8c-49da-9dff-40fe53d6d683)
It works fine most of the time as the error correction easily compensates those pixels.
But in some cases, when the higlight happens to be at an important area, like the center of an alignment pattern, it produces hard to read codes.

**Describe the solution you'd like**
The paint method of QrVectorColor and the shape method of QrVectorPixelShape should have an additional input parameter that gives some extra information about the current pixel.
This could either be a boolean that states if it belongs to a reserved area or an int that works like an enum stating exactly to which area it belongs.

The different reserved areas are:
- Alignment pattern
- timing pattern
- dark module
- version information
- format information

Please refer to this page:
https://www.thonky.com/qr-code-tutorial/module-placement-matrix

**Describe alternatives you've considered**
The alternative would be to not use any highlights or to use a darker color. But I want to use my apps accent color and I like the way it looks now.

**Comment by alexzhirkevich** [comment]
You can set highlighting for important areas using `highlighting` block in DSL builder.

**Comment by michaelWuensch** [comment]
Ok thanks, I'll check that later. But I think it is something different. My background is already white.
I want single pixels to have that bright color, but none of the important pixels.
I could easily do this if the additional parameter was exposed.
And my solution would also allow for even more customization like having squares for the alignment patterns while having circles for the rest etc...

**Comment by alexzhirkevich** [comment]
It allows to set different shape and color for pixels from important areas. But it's customization is limited.  It probably can be extended

**Comment by alexzhirkevich** [comment]
>The paint method of QrVectorColor ... should have an additional input parameter that gives some extra information about the current pixel.

It is impossible because in most of cases paint created for the whole dark/light pixels at once (not for one pixel).

**Comment by michaelWuensch** [comment]
Makes sense. In theory wold't it be possible to just set this parameter to null/false/unavailable or something like that for all cases where all pixels are drawn at once?
But I am not too deep into your code, maybe there are more elegant solutions.

**Comment by michaelWuensch** [comment]
I am actually very close now.
I changed my approach to have all dark pixels dark and add the accent color in the bright pixels.
So instead of turning some of the black pixels to yellow I turn some of the white pixels to yellow.
The highlighting feature can then be used to ensure some pixels stay white.
This way I was able to protect the eyes and the timing pattern, but I can't get the version eyes to look correct, as the highlight also overrides some of the dark pixels (the frame of the eye).

**Comment by alexzhirkevich** [comment]
Highlighting will be extended in the next version and will allow to set shape and color of the highlighting as well as shape and color of the element being highlighted

**Comment by alexzhirkevich** [comment]
Currently shape of version eye aka alignment pattern is combined from `frame` and `ball` of corner eyes as well as it's color as far as i remember

**Comment by alexzhirkevich** [comment]
> the 1 pixel frame of the version eye vanishes completely 

It is a result of applying rounded corner shape designed for 7-pixel eye to 5-pixel eye (bug)

**Comment by alexzhirkevich** [comment]
> the 1 pixel frame of the version eye vanishes completely 

It is a result of applying rounded corner shape designed for 7-pixel eye to 5-pixel eye (bug). It works fine with other frame shapes

**Comment by alexzhirkevich** [comment]
This should help if you rollback to random colors in dark pixels

```kotlin
highlighting {
    timingLines = HighlightingType.Styled(
        color = QrVectorColor.Unspecified,
        elementShape = /*your dark pixel shape goes here*/,
        elementColor =  /*your dark pixel color without randomness goes here*/
    )
    versionEyes = HighlightingType.Styled(
        color = QrVectorColor.Unspecified,
        elementShape = QrVersionEyeShape(
            frame = QrVectorFrameShape.AsPixelShape(
                pixelShape = /*your dark pixel shape goes here. */,
                size = 5
            ),
            ball = /*your dark pixel shape goes here. 
                   you can use same ball shape or call pixelShape.asBallShape() */
        ),

        elementColor =  /*your dark pixel color without randomness goes here*/
    )
}
```

**Comment by michaelWuensch** [comment]
Hi,
I tried to implement the changes, but had to leave for work before I was finished.
As I use the library from within java, my implementation alway looks a bit different.
Timing pattern highlight already worked like a charm!
I was about to do the versionEye highlight when I had to leave. But it seemed there was no QrVersionEyeShape()  at all.
Anyway, I'll work on it again tomorrow.
Thanks for all your help!

**Comment by alexzhirkevich** [comment]
Its a function inside QrHighlighting.kt so you have to use `QrHighlightingKt.QrVersionEyeShape` i guess

**Comment by alexzhirkevich** [comment]
.asBallShape() is an extension from QVectorShapeUtils.kt (withourt 'r', wrongly named, will be changed)

**Comment by michaelWuensch** [comment]
Hi,
everything works as expected!!
Thanks!
