### ISSUE TITLE
Customizing QR code after generation

### ISSUE THREAD

**Issue by MuhammadSaad420** [alexzhirkevich/custom-qr-generator#39]
I am generating QR code using zxing library...after generating, i am getting a bitmap image...can i edit QR code in the bitmap image in future instead of generating it again?

**Comment by alexzhirkevich** [comment]
What do you mean by edit?

**Comment by MuhammadSaad420** [comment]
like generating QR code with MultiformatWriter and generating a bitmap(with default black QR pixels)....and in future Editing the bitmap(like changing the background of QR image, changing shape of QR pixel) when user wants to instead of generating the QR code again

**Comment by alexzhirkevich** [comment]
You can convert drawable to bitmap and do with it what you want. Anyway generating takes ~30ms. I guess your pixel-by-pixel editing takes a lot longer

**Comment by MuhammadSaad420** [comment]
ok
