### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by RoyalCoder88** [alexzhirkevich/custom-qr-generator#4]
Hi Alex,

Thanks for this amazing example project, can you add support for Flutter for Custom Qr Generator?
I think will be amazing for pub.dev community!

Thanks in advance!

**Comment by alexzhirkevich** [comment]
> Hi Alex,
> 
> Thanks for this amazing example project, can you add support for Flutter for Custom Qr Generator? I think will be amazing for pub.dev community!
> 
> Thanks in advance!

HI, Dorin.

Thanks for your support. I have a prototype written in pure Kotlin (without dependencies) with Kotlin Multiplatform support. But I don't have experience in developing and publishing flutter packages. If you want, I can publish this prototype and you can help me to rewrite it to Dart and publish it

**Comment by RoyalCoder88** [comment]
@alexzhirkevich I will be glad to help with what I can ;)

**Comment by RoyalCoder88** [comment]
Hi @alexzhirkevich , any news? Thanks!

**Comment by alexzhirkevich** [comment]
> Hi @alexzhirkevich , any news? Thanks!

Hi, @RoyalCoder88. KMM prototype doesn't work now. I think I made mistake somewhere during converting ZXing java classes to kotlin. Generated codes are unscannable. Besides, I used abstract ARGB bitmap in common code and converting it to IOS UIImage takes too long time (about 20 sec on real device). And some more bugs on IOS like black logo sometimes turn green... May be it is easier to write dart version of it instead of trying to use KMM. Like I see, dart also has [zxing library](https://pub.dev/packages/zxing2)

**Comment by alexzhirkevich** [comment]
Do you really need a flutter version of it for some project?

**Comment by RoyalCoder88** [comment]
Hi @alexzhirkevich ,

Yes, I really need asap this kind of QR Generator for Flutter, and I think will be an amazing package on pub.dev!
Have a great day my friend, and keep up the good work!

**Comment by alexzhirkevich** [comment]
> Hi @alexzhirkevich ,
> 
> Yes, I really need asap this kind of QR Generator for Flutter, and I think will be an amazing package on pub.dev! Have a great day my friend, and keep up the good work!

Ok, i'll check what i can do. It would be good if you give me an equivalent of android [Bitmap](https://developer.android.com/reference/android/graphics/Bitmap) in flutter, which can be displayed, mb saved to file and important with pixel by pixel processing ability

**Comment by RoyalCoder88** [comment]
Hi Alex, do you mean a **QR Viewer** or **Image generator**?

**Comment by RoyalCoder88** [comment]
Hi @alexzhirkevich , hope you're well any news about the flutter version? Thanks in advance!

**Comment by alexzhirkevich** [comment]
Hi, @RoyalCoder88 

Vector codes with basic shapes and colors are working now. I am working on a logo. You can contribute [here](https://github.com/alexzhirkevich/custom-qr-generator-flutter)

**Comment by RoyalCoder88** [comment]
Great job Alex, thanks!

**Comment by RoyalCoder88** [comment]
Hi @alexzhirkevich ,

I tested you did a great job, please add support for adding the logo image in the center of the code, thanks in advance!

**Comment by alexzhirkevich** [comment]
Hi, @RoyalCoder88,

Why don't just place logo widget on top of qr code image? 

And please make future enhancement suggestions in [flutter](https://github.com/alexzhirkevich/custom-qr-generator-flutter) repo.
