### ISSUE TITLE
Is the size of the positioning markings adjustable?

### ISSUE THREAD

**Issue by MariusBudin** [alexzhirkevich/custom-qr-generator#40]
**Describe the option you are trying to implement**
I want to create QR code with smaller positioning markings (the 3 shapes on the top left and right and bottom left)

Is there any way to adjust the size of them and let the content grow a bit more?

Thanks for the library! Awesome job!

**Comment by alexzhirkevich** [comment]
The size of positional eyes is defined by QR code standard - 7 dots. You can make its middle ball smaller/bigger and frame stoke thinner/thicker but not the size of it in general

**Comment by alexzhirkevich** [comment]
Technically you can create custom shapes and use any size you want for it ignoring one that comes as a parameter, but there is no guarantee you would able to scan such a code

**Comment by alexzhirkevich** [comment]
And in v2.0 alpha there is a magic function `scale` that you can apply to any shape and combining with `.asBalShape()` / `asFrameShape` you can create scaled shapes with center pivot. But again this can negatively reflect on the functionality of this code

**Comment by MariusBudin** [comment]
Understood, thank you very much for your replies! 🍻 
The issue I had was data was too small so there were few dots and large positioning markings and it looked a bit weird. I've added some correction level so it generates more points and it pushed them a bit and scaled down, and looks better now.
Good info you shared, I'll try to avoid it for now, just to make sure I'm not affecting functionality for aesthetics
