### ISSUE TITLE
Any Java samples?

### ISSUE THREAD

**Issue by YohannesTz** [alexzhirkevich/custom-qr-generator#45]
I am trying to implement a custom QR like the ones provided in the examples (Instagram to be specific) code in Java. I have attempted to use the builder but was not successful.

can any one provide me with examples?

thanks.

**Comment by alexzhirkevich** [comment]
These example are outdated, they use deprecated features. 
There are no java examples in this repo but you can find something useful [here](https://github.com/michaelWuensch/BitBanana/blob/master/app/src/main/java/app/michaelwuensch/bitbanana/qrCodeGen/QRCodeGenerator.java)

**Comment by YohannesTz** [comment]
thanks. I will take a look!

**Comment by YohannesTz** [comment]
thanks! I got something working!
