### ISSUE TITLE
overlay image on qrCode

### ISSUE THREAD

**Issue by chuongdk2011** [alexzhirkevich/custom-qr-generator#51]
Can the library support doing something like this?:

![image](https://github.com/alexzhirkevich/custom-qr-generator/assets/118891109/c6c9ba1b-8c63-4b9e-bd23-a9b7a397bfbb)
![image](https://github.com/alexzhirkevich/custom-qr-generator/assets/118891109/d41ccd39-a032-4c0d-96f4-c385d099bf5f)

**Comment by alexzhirkevich** [comment]
You can do 

```kotlin
val options = createQrVectorOptions {
    colors {
        dark = QrVectorColor.Eraser
    }
    background {
        color = QrVectorColor.Solid(Color.WHITE)
    }
}
```

This will create drawable where QRcode is cut from white background. Then you can place this drawable above any other View and this view will be visible throught the holes

Or you can merge your image and this drawable using 

```kotlin
val resultDrawable  = LayerDrawable(arrayOf(imageDrawable, qrCodeDrawable))
```

**Comment by alexzhirkevich** [comment]
Or you can use this to just cut QR code from your provided `imageDrawable`

```kotlin
val options = createQrVectorOptions {
    colors {
        light = QrVectorColor.Eraser
        dark = QrVectorColor.Transparent
    }
    background {
        drawable = imageDrawable
    }
}
```

**Comment by chuongdk2011** [comment]
I tried the above codes, but my idea is to overlay the image on the places where the QrCode is, like set a color for the QrCode, and the remaining parts that don't have the Qrcode will show up in the default background color.

**Comment by chuongdk2011** [comment]
It seems your code above is doing the opposite.

**Comment by alexzhirkevich** [comment]
You can't overlay an image. You can only cut QR code from background and make a LayerDrawable with your image

**Comment by alexzhirkevich** [comment]
You can create custom `QrVectorColor` and make a shader`Paint` using `BitmapShader` from your image

**Comment by alexzhirkevich** [comment]
Here is an example:
```kotlin
class QrImageColor(private val image : Drawable) : QrVectorColor {
    override fun createPaint(width: Float, height: Float): Paint {
        val bitmap = image.toBitmap(width.roundToInt(),height.roundToInt())
        val bitmapShader = BitmapShader(bitmap, Shader.TileMode.CLAMP, Shader.TileMode.CLAMP)
        return Paint().apply {
            shader = bitmapShader
        }
    }
}
```

**Comment by alexzhirkevich** [comment]
@chuongdk2011  Doest it fit your needs?

**Comment by chuongdk2011** [comment]
Yes, I did it. Thank you very much
