### ISSUE TITLE
Help Implementing

### ISSUE THREAD

**Issue by gregnomis** [alexzhirkevich/custom-qr-generator#53]
Sorry for the noob question, new dev here!
I am using this version:
implementation ("com.github.alexzhirkevich:custom-qr-generator:2.0.0-alpha01")

jitpack is in my settings.gradle
maven("https://jitpack.io")

Yet theres a problem importing some functions:
import com.github.alexzhirkevich.customqrgenerator.QrData
import com.github.alexzhirkevich.customqrgenerator.**_createQrVectorOptions_**
import com.github.alexzhirkevich.customqrgenerator.**_dsl_**.QrVectorLogoShape

Unresolved reference: createQrVectorOptions
Unresolved reference: dsl

Am I missing something?

**Comment by gregnomis** [comment]
Still learning my way around the library;
changed import com.github.alexzhirkevich.customqrgenerator.createQrVectorOptions
to import com.github.alexzhirkevich.customqrgenerator.**_vector_**.createQrVectorOptions

**Comment by alexzhirkevich** [comment]
Open 2.0 branch and check **app** example

**Comment by alexzhirkevich** [comment]
[here](https://github.com/alexzhirkevich/custom-qr-generator/blob/v2.0/app/src/main/java/com/github/alexzhirkevich/customqrgenerator/MainActivity.kt)

**Comment by gregnomis** [comment]
Thank you!! Starting to figure things out, Literally my first year coding, still learning everything. Thanks!
