### ISSUE TITLE
Incorrect coding Cyrillic letters

### ISSUE THREAD

**Issue by krauzee** [alexzhirkevich/custom-qr-generator#6]
When I generate a VCard QR code with a name in Cyrillic letters, when I scan the code, the name "Роман" became "?????", but if I set the name as "Roman", the code works correctly

**Comment by alexzhirkevich** [comment]
Hi, thanks for contributing.

Fixed in 1.5.1. Now you can choose charset in `QrCodeDrawable` and `QrCodeGenerator.generateQrCode` methods.
UTF-8 works fine with Cyrillic letters, but can slightly increase QR code size.

**Comment by krauzee** [comment]
thank you very much!
