### ISSUE TITLE
Gradient background

### ISSUE THREAD

**Issue by donatkajtazi** [alexzhirkevich/custom-qr-generator#7]
Is there a way that we can make a gradient background that fills the whole qr

**Comment by alexzhirkevich** [comment]
> Is there a way that we can make a gradient background that fills the whole qr

For Bitmap QR code you can just set background color to gradient in options:

```kotlin
val options = createQrOptions(1024) {
    background {
        color = QrColor.LinearGradient(
            android.graphics.Color.RED, android.graphics.Color.BLUE,
            QrColor.LinearGradient.Orientation.LeftDiagonal
        )
    }
}
```

For Drawable QR code you can do it like that:

```kotlin
  val gradientDrawable = GradientDrawable(
      GradientDrawable.Orientation.TL_BR,
      intArrayOf(android.graphics.Color.RED, android.graphics.Color.BLUE)
  )
  val codeDrawable = QrCodeDrawable(context, data, anyOptions)
  
  val codeWithGradientBg = LayerDrawable(arrayOf(gradientDrawable, codeDrawable))
```

**Comment by alexzhirkevich** [comment]
Is that what you need, @donatkajtazi?

**Comment by donatkajtazi** [comment]
> Is that what you need, @donatkajtazi?

looks like it was there all along I just didn't find it

**Comment by alexzhirkevich** [comment]
Background image and color for Drawable codes (without LayerDrawable) will be supported in the next update
