### ISSUE TITLE
GIF Support

### ISSUE THREAD

**Issue by hardikbhalodi** [alexzhirkevich/custom-qr-generator#8]
is it possible to add GIF image as foreground of QR Code?

**Comment by alexzhirkevich** [comment]
Gif animation is not supported. You can set 1 frame from gif as a foreground.

**Comment by hardikbhalodi** [comment]
is it possible to implement with this library?

**Comment by alexzhirkevich** [comment]
It technically possible, but what means "foreground of the QR code"? 

1st or 2nd? or even something else?
<p float="left">
  <img src="https://user-images.githubusercontent.com/63979218/207724563-5bc16c23-b7a7-4cf8-83e8-019e77e30a64.gif" width="200" />
  <img src="https://user-images.githubusercontent.com/63979218/207724589-c8f4c8ca-d43c-4e36-a107-ccd6fe652f9b.gif" width="200" /> 
</p>

**Comment by hardikbhalodi** [comment]
Yes the 1st is correct. here is one more example of same
![gif](https://user-images.githubusercontent.com/4948894/207771512-4411a068-c8da-41af-b241-eb0e1f10d069.gif)

**Comment by alexzhirkevich** [comment]
Tbh, your example looks more like 2nd variant.

You can achieve the like this:
```kotlin
LayerDrawable(
    arrayOf(
        QrCodeDrawable(context, data,options),
        GifDrawable(resources, R.drawable.gif).apply {
            alpha = 125
        }
    )
)
```
(Leave QR code background transparent by default)

**Comment by hardikbhalodi** [comment]
Okay thank you.. i will try

**Comment by hardikbhalodi** [comment]
Could not resolve 1.5.4 version dependency 

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.alexzhirkevich:custom-qr-generator:1.5.4.

**Comment by alexzhirkevich** [comment]
> Could not resolve 1.5.4 version dependency
> 
> Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.alexzhirkevich:custom-qr-generator:1.5.4.

Works fine for me. Mb you removed jitpack repository from your gradle file. Btw, this version doesn't have anything related to gifs

**Comment by hardikbhalodi** [comment]
Yes i know this version do not have gif support but i want to implement
bitmap shader using QRVectorColor interface which is "sealed interface" in
1.5.3 version so i could not extend it.

By the way i have jitpack.io repo in gradle file but for 1.5.4 version
getting could not resolve but 1.5.3 working fine.

**Comment by alexzhirkevich** [comment]
I rebuilt it on jitpack. If it doesn't help you can try clean gradle caches folder (.gradle/caches) and again download 1.5.3 and 1.5.4 versions.

**Comment by hardikbhalodi** [comment]
Thanks, I'll check it out.

**Comment by hardikbhalodi** [comment]
How to create eyes like this? i could able to write custom shape but same
shape would applied to all side.

**Comment by hardikbhalodi** [comment]
How to customise eyes like this, i tried and able to customise with same shape but all the sides are same!
![unitag_qrcode_standard](https://user-images.githubusercontent.com/4948894/210740615-389e71e3-9184-4902-a406-dd5365255a9f.png)

**Comment by alexzhirkevich** [comment]
Please create new issues for different questions
