### ISSUE TITLE
Ambiguous method call

### ISSUE THREAD

**Issue by ruinalgo** [alexzhirkevich/custom-qr-generator#9]
It is not possible to use `QrVectorOptions.Builder` from java side.
Decompiler shows identical setters for all fields inside builder.
![qrcg_issue](https://user-images.githubusercontent.com/21956677/207588851-d6e86306-5a40-4ae1-a653-5be1997aaf77.png)

version used: 1.5.3

**Comment by alexzhirkevich** [comment]
Will be fixed in next updates. For now you can use `QrVectorOptions` constructor directly instead of builder

**Comment by alexzhirkevich** [comment]
Fixed in 1.5.4
